### ISSUE TITLE
quartermaster 0.11.4: CLI fails to load, scripts/quality/quartermaster-crap.cjs is not shipped

### ISSUE THREAD

**Issue by DanielHeinz7** [Eigenwise/eigenwise-toolshed#261]
In 0.11.4, `lib/crap.js` is `module.exports = require('../../../scripts/quality/quartermaster-crap.cjs')`. That path points outside the plugin directory, and the published plugin doesn't ship it. `bin/quartermaster.js` requires `lib/crap.js` at top level, so every subcommand fails on load, not just `crap`: `--help`, `mine`, `decline-resupply` and `mark-resupply` all throw

```
Error: Cannot find module '../../../scripts/quality/quartermaster-crap.cjs'
```

As a result, `/quartermaster:resupply` can't run at all.

**Repro:** install quartermaster 0.11.4 from the marketplace, then run `node <plugin root>/bin/quartermaster.js --help`. The same command works on 0.11.2.

**Likely cause:** the 0.11.4 change "Align CRAP gates with the strict six-point standard", which switched to a shared quality parser that lives in the monorepo but not in the plugin package. A fix would bundle the parser inside the plugin, or load `lib/crap.js` lazily inside the `crap` subcommand so the other commands keep working.

**Comment by DanielHeinz7** [comment]
Confirmed on macOS with Node 24.16.0. Beyond the subcommands listed above, `verify`, `catalog --installed` and `decisions list` fail the same way, each with `Cannot find module '../../../scripts/quality/quartermaster-crap.cjs'` and exit 1.

One consequence the report doesn't mention: the Stop-time resupply offer still fires on 0.11.4, since that hook doesn't load `lib/crap.js`. The user is offered a round that cannot start, and the documented way to decline it (`decline-resupply`) fails too, so the offer can't be backed off either. Accepting it fails at the first step, `mine`.

The missing file is present in the marketplace checkout under `scripts/quality/`, just not in the installed plugin, which fits the packaging explanation above. 0.11.2 still runs `mine` normally on the same machine.

**Comment by cobrahjh** [comment]
Independent confirmation on Windows 11 after refreshing the Eigenwise Toolshed marketplace and running the updater:

- Quartermaster: `0.11.4` (user scope; updater reports it is still the latest release)
- Claude Code: `2.1.280`
- Node.js: `v22.23.2`

A non-CRAP command fails before argument handling:

```text
node "%USERPROFILE%\.claude\plugins\cache\eigenwise-toolshed\quartermaster\0.11.4\bin\quartermaster.js" catalog --installed

Error: Cannot find module '../../../scripts/quality/quartermaster-crap.cjs'
Require stack:
- <plugin cache>\quartermaster\0.11.4\lib\crap.js
- <plugin cache>\quartermaster\0.11.4\bin\quartermaster.js
```

This also blocks `/quartermaster:setup`: the skill itself loads, but its required `mine --all-projects`, `catalog --installed`, decision recording, and CRAP verification commands cannot start. The missing module is present in the marketplace checkout under `scripts/quality/`, but not in the installed plugin cache, matching the packaging diagnosis above.

No local cache patch was applied.

**Comment by smallworldmedia** [comment]
Also reproduced on macOS 15.7.3 with Node v26.3.1 and Claude Code 2.1.281. The installed 0.11.4 fails on `mine` and `verify` with the same `Cannot find module '../../../scripts/quality/quartermaster-crap.cjs'`.

One addition that may help others until a fixed release ships: `bin/quartermaster.js` from the same 0.11.4 version inside the marketplace checkout (`<marketplaces>/eigenwise-toolshed/plugins/quartermaster/bin/quartermaster.js`) runs normally. From there the relative path resolves to the checkout's `scripts/quality/`. With it, `mine`, `verify`, `allowlist`, `decisions add` and `crap` all completed a full resupply round. This is a manual stopgap, not a fix, and hook or skill invocations that point at the cache path still fail.
